### ISSUE TITLE
Länken "Personalavin" inte borttagen överallt

### ISSUE THREAD

**Issue by elilun14** [malmostad/global_assets#10]
Den visas fortfarande när man står i Wikin och i Webbvideo.

**Comment by martent** [comment]
My bad. Glömde ändra i den gamla Global Assets v3 som wikin fortfarande använder. Den var inte rör på ett par år, v4 är den aktuella.

Nu ska det vara fixat. Jag kan inte verifiera webbvideo utifrån, hamnar på den externa versionen, men wikin är verifierad.

**Comment by elilun14** [comment]
Hej! Ok så wikin använder inte samma Asset som resten? 
Jag kollade Webbvideo och ser inte längre Personalavilänken där, så det verkar ok. 
Hag stänger detta ärende. //

**Comment by martent** [comment]
> Ok så wikin använder inte samma Asset som resten? 

Nej wikin är inte uppdaterad till WAG v4 utan ligger kvar i v3. Den ligger lite utanför de andra webbapparna eftersom den anpassades och sattes upp hastigt under en dag och inte har rörts tekniskt sen dess. Har tidigare informerat @magnivar att man bör fundera igenom Wikins tekniska uppsättning och anpassning till WAG:n.

Mediawiki, som Wikipedias system heter och som ni använder, är lite speciell när det gäller anpassningar. De flesta organisationer som använder den gör inget mer än att lägga på sitt sidhuvud. Den är inte avsedd att göras så mycket mer med utan har i övrigt oftast Wikipedias utseende.
