### ISSUE TITLE
Placering av cookie disclaimern på vuxwebben

### ISSUE THREAD

**Issue by olajoh1** [malmostad/global_assets#11]
AGV-förvaltningen har följande problem, möjligt att åtgärda?

Hej, vi har ett problem med den Cookie disclaimer, som ligger på http://vuxenutbildning.malmo.se/ idag, rutan ”jag förstår” som man ska kunna klicka i för att godkänna cookies lägger sig under chatt rutan. Är det möjligt att man lägger Cookie disclamern i ovankant av webbläsaren på just vuxenutbildningssidan? Detta är inget som vi styr över så som jag har förstått det så behöver det gå via er.

**Comment by martent** [comment]
Vi kan inte lägga den i ovankant eftersom vi inte vet vad andra av Malmö stads webbtjänster har där på sina sidor.

Cookie-consent har z-index 9999 medan chattrutan har det extrema värdet 107158. Ange z-index till ett värde under 9999 så hamnar den under, t.ex. `z-index: 1`. Vilket legalt är det rimliga, man måste godkänna cookies innan man kan chatta.

**Comment by olajoh1** [comment]
tack
