### ISSUE TITLE
Problems with occasional white in video thumbnails in dashboard

### ISSUE THREAD

**Issue by jesperbylund** [malmostad/global_assets#5]
![vitt i tumnagen pa video](https://cloud.githubusercontent.com/assets/3509721/15501060/d92e389c-21ab-11e6-9f9f-fbaf1fd17215.JPG)

Sometimes the thumbnails is displayed wrong at "Min sida", see screen shot.

**Comment by magnivar** [comment]
Kolla om det går att återskapa felet.

**Comment by magnivar** [comment]
löst av sig själv
