### ISSUE TITLE
Masthead error: t.cookie is not a function

### ISSUE THREAD

**Issue by johanlahti** [malmostad/global_assets#7]
When visiting http://malmo.se/karta their is an error in the file: masthead_standalone_without_jquery.js

```
masthead_standalone_without_jquery.js?_=1466438834752:15 Uncaught TypeError: t.cookie is not a function
```

Here is how we add the masthead: https://github.com/getsmap/smap-responsive/blob/master/plugins/MalmoHeader/MalmoHeader.js

**Comment by martent** [comment]
This was because the jQuery.cookie plugin wasn't included in `masthead_standalone_without_jquery.js`.

No errors are raised from Malmös Global Assets now, as far as I can see.

cc: @magnivar

**Comment by johanlahti** [comment]
👍
