### ISSUE TITLE
Ta bort "Personalavin" ur toppmenyn Komin

### ISSUE THREAD

**Issue by elilun14** [malmostad/global_assets#9]
I Komins toppmeny finns Mer > Personalavin, den sistnämnda länken (tydligen hårdkodad) ska tas bort då denna inte finns längre och länken ger felmeddelande.

**Comment by martent** [comment]
Vill du att jag pekar om länken eller menyvalet ska bort helt?

Länkarna i toppmenyn är halvdynamiska, de pekar mot s.k. alias i Sitevision där de sen styrs till den adress man ställer in i Sitevision (gäller inte för valet Personalavin ser jag, borde varit komin.malmo.se/personalavin som alias i SV).

I övrig mening är toppmenyn som du skriver hårdkodad vilket beror på att alla webb-system får in den via Javascriptet de länkar in från Global Assets. Det var en mer dynamisk lösning tidigare men en del leverantörer klarade inte av att implementera den, därav denna förenkling i version 4 av Global Assets.

cc @magnivar

**Comment by elilun14** [comment]
Den ska bort helt. @martent

**Comment by martent** [comment]
Borttagen. Vissa användaren kan eventuellt se den under dagen eftersom filen kan cachas i webbläsaren.

**Comment by elilun14** [comment]
Fixat.
